<a href="https://colab.research.google.com/github/keshav123333/amazon-ml/blob/main/Amazon_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
url="http://raw.githubusercontent.com/dixitkeshav/AMAZON_ML/refs/heads/main/new/student_resource/dataset/train.csv"
df_train=pd.read_csv(url)

In [3]:
df_train

,sample_id,catalog_content,image_link,price
0,33127,"Item Name: La Victoria Green Taco Sauce Mild, ...",https://m.media-amazon.com/images/I/51mo8htwTH...,4.890
1,198967,"Item Name: Salerno Cookies, The Original Butte...",https://m.media-amazon.com/images/I/71YtriIHAA...,13.120
2,261251,"Item Name: Bear Creek Hearty Soup Bowl, Creamy...",https://m.media-amazon.com/images/I/51+PFEe-w-...,1.970
3,55858,Item Name: Judee’s Blue Cheese Powder 11.25 oz...,https://m.media-amazon.com/images/I/41mu0HAToD...,30.340
4,292686,"Item Name: kedem Sherry Cooking Wine, 12.7 Oun...",https://m.media-amazon.com/images/I/41sA037+Qv...,66.490
...,...,...,...,...
74995,41424,Item Name: ICE BREAKERS Spearmint Sugar Free M...,https://m.media-amazon.com/images/I/81p9PcPsff...,10.395
74996,35537,"Item Name: Davidson's Organics, Vanilla Essenc...",https://m.media-amazon.com/images/I/51DDKoa+mb...,35.920
74997,249971,Item Name: Jolly Rancher Hard Candy - Blue Ras...,https://m.media-amazon.com/images/I/91R2XCcpUf...,50.330
74998,188322,Item Name: Nescafe Dolce Gusto Capsules - CARA...,https://m.media-amazon.com/images/I/51W40YU98+...,15.275
74999,298504,Item Name: Pimenton de la Vera - Picante (2.47...,https://m.media-amazon.com/images/I/81dFnrP6C4...,28.240

In [6]:
df_train["catalog_content"][1]

'Item Name: Salerno Cookies, The Original Butter Cookies, 8 Ounce (Pack of 4)\nBullet Point 1: Original Butter Cookies: Classic butter cookies made with real butter\nBullet Point 2: Variety Pack: Includes 4 boxes with 32 cookies total\nBullet Point 3: Occasion Perfect: Delicious cookies for birthdays, weddings, anniversaries\nBullet Point 4: Shareable Treats: Fun to give and enjoy with friends and family\nBullet Point 5: Salerno Brand: Trusted brand of delicious butter cookies since 1925\nValue: 32.0\nUnit: Ounce\n'

In [ ]:
import os
import requests
from PIL import Image
from io import BytesIO
from tqdm.notebook import tqdm
import pandas as pd # Make sure to have your dataframe loaded, e.g., df_train

# --- KEY CHANGE: Save images to your Google Drive for persistence ---
# This folder will be created inside 'My Drive'
GDRIVE_IMAGE_DIR = '/content/drive/MyDrive/smart_product_pricing_images'
os.makedirs(GDRIVE_IMAGE_DIR, exist_ok=True)

# Let's assume df_train is your training dataframe
# df_train = pd.read_csv('dataset/train.csv')

downloaded_image_paths = {}
error_count = 0

# --- KEY CHANGE: Use tqdm for a progress bar ---
# We iterate over a list of tuples for better performance with tqdm
image_list = list(df_train[['sample_id', 'image_link']].itertuples(index=False, name=None))

for sample_id, image_link in tqdm(image_list, desc="Downloading Images"):
    image_path = os.path.join(GDRIVE_IMAGE_DIR, f'{sample_id}.jpg') # Save as JPG for efficiency
    downloaded_image_paths[sample_id] = image_path # Store the path for later use

    # --- KEY CHANGE: Skip if the image already exists ---
    if os.path.exists(image_path):
        continue # Don't download again

    try:
        response = requests.get(image_link, timeout=10)
        response.raise_for_status()

        if 'image' in response.headers.get('Content-Type', ''):
            image = Image.open(BytesIO(response.content))

            # --- OPTIMIZATION: Resize image to save space and standardize for ML models ---
            image = image.convert('RGB') # Convert to RGB to avoid issues with transparency (PNG)
            resized_image = image.resize((224, 224))
            resized_image.save(image_path, 'JPEG') # Save as JPEG

        else:
            # Silently skip non-image content or handle as needed
            error_count += 1

    except (requests.exceptions.RequestException, IOError):
        # Silently skip download/processing errors
        error_count += 1


print("\n--- Download Summary ---")
print(f"Image directory: {GDRIVE_IMAGE_DIR}")
print(f"Total images in dataframe: {len(df_train)}")
# Count how many files were actually saved in the directory
successful_downloads = len(os.listdir(GDRIVE_IMAGE_DIR))
print(f"Images successfully saved in Drive: {successful_downloads}")
print(f"Errors or non-image links skipped: {error_count}")

Downloading Images:   0%|          | 0/5000 [00:00<?, ?it/s]

--- Download Summary ---
Image directory: /content/drive/MyDrive/smart_product_pricing_images
Total images in dataframe: 5000
Images successfully saved in Drive: 5000
Errors or non-image links skipped: 0

In [4]:
from transformers import AutoTokenizer,AutoModel
import torch
from tqdm import tqdm

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch
from tqdm import tqdm

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch
from tqdm import tqdm
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Better model
tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/all-mpnet-base-v2")
model1 = AutoModel.from_pretrained("sentence-transformers/all-mpnet-base-v2").to(device)
model1.eval()

def get_text_embeddings_mpnet(texts):
    embeddings = []
    for text in tqdm(texts):
        inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=256).to(device)
        with torch.no_grad():
            outputs = model1(**inputs)
            emb = outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
            embeddings.append(emb)
    return embeddings

# text_features = get_text_embeddings_mpnet(df_train['catalog_content'].tolist())

ye dusra

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")
model1 = AutoModel.from_pretrained("sentence-transformers/all-MiniLM-L6-v2").to(device)
model1.eval()

def get_text_embeddings_all_Mini(texts):
    embeddings = []
    for text in tqdm(texts):
        inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=128).to(device)
        with torch.no_grad():
            outputs = model1(**inputs)

            emb = outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
            embeddings.append(emb)
    return embeddings

text_features = get_text_embeddings_all_Mini(df_train['catalog_content'].tolist())

100%|██████████| 75000/75000 [07:04<00:00, 176.49it/s]

effiecent net

if link se direct laani hai toh

In [ ]:
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image
import requests
from io import BytesIO
from tqdm import tqdm

effnet = EfficientNetB0(weights='imagenet', include_top=False, pooling='avg')

def get_image_embedding_effnet_imageLink(img_url):
    try:
        response = requests.get(img_url, timeout=8)
        if response.status_code != 200:
            raise ValueError("Bad response")
        img = Image.open(BytesIO(response.content)).convert('RGB')
        img = img.resize((224, 224))
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        x = preprocess_input(x)  # very important
        feat = effnet.predict(x, verbose=0)
        return feat.flatten()
    except Exception as e:
        print(f"⚠️ Failed: {img_url} | {e}")
        return np.zeros((1280,))

# Example:
image_features = [get_image_embedding_effnet_imageLink(url) for url in tqdm(df_train['image_link'])]
image_features = np.array(image_features)

print("Shape:", image_features.shape)
print("Max value:", image_features.max())
print("Zero vectors:", np.sum(np.all(image_features == 0, axis=1)))

In [ ]:
image_features.shape

(10000, 1280)

for if pehle download kar lo toh

In [ ]:
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.preprocessing import image
import numpy as np
import os
from tqdm import tqdm
from PIL import Image

# Path to your image folder
image_folder = '/content/drive/MyDrive/smart_product_pricing_images'

# Load EfficientNetB0 (no top layer, global avg pooling)
effnet = EfficientNetB0(weights='imagenet', include_top=False, pooling='avg')

def get_image_embedding_from_path(img_path):
    try:
        img = Image.open(img_path).convert('RGB')
        img = img.resize((224, 224))  # EfficientNetB0 expects 224x224
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        x = preprocess_input(x)
        feat = effnet.predict(x, verbose=0)
        return feat.flatten()
    except:
        return np.zeros((1280,))  # EfficientNetB0 outputs 1280-dim features

# Get all image paths
image_paths = [os.path.join(image_folder, f)
               for f in os.listdir(image_folder)
               if f.lower().endswith(('png', 'jpg', 'jpeg'))]

# Extract features
image_features = []
for path in tqdm(image_paths):
    image_features.append(get_image_embedding_from_path(path))

image_features = np.array(image_features)
print("Shape of image features:", image_features.shape)

Downloading data from https://storage.googleapis.com/keras-applications/efficientnetb0_notop.h5
16705208/16705208 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step

100%|██████████| 5000/5000 [06:55<00:00, 12.04it/s]

Shape of image features: (5000, 1280)

In [ ]:
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.preprocessing import image
import numpy as np
import os
from tqdm import tqdm
from PIL import Image

# Path to your folder containing 5000 images
image_folder = '/content/drive/MyDrive/smart_product_pricing_images'

# Load VGG16 model (without top layers, with avg pooling)
vgg = VGG16(weights='imagenet', include_top=False, pooling='avg')  # Output: 512-dim vector

def get_image_embedding_from_path(img_path):
    try:
        img = Image.open(img_path).convert('RGB')
        img = img.resize((224, 224))  # VGG16 input size
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        x = preprocess_input(x)
        feat = vgg.predict(x)
        return feat.flatten()
    except:
        # Return zeros if image can't be read
        return np.zeros((512,))

# Get list of image paths
image_paths = [os.path.join(image_folder, fname) for fname in os.listdir(image_folder) if fname.lower().endswith(('png','jpg','jpeg'))]

# Extract embeddings
image_features = []
for path in tqdm(image_paths):
    image_features.append(get_image_embedding_from_path(path))

# Convert to numpy array if needed
image_features = np.array(image_features)
print("Shape of image features:", image_features.shape)

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5
58889256/58889256 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step

  0%|          | 0/1000 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step

  0%|          | 1/1000 [00:04<1:08:21,  4.11s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

  0%|          | 2/1000 [00:04<33:58,  2.04s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

  0%|          | 3/1000 [00:05<24:24,  1.47s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  0%|          | 4/1000 [00:06<18:38,  1.12s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

  0%|          | 5/1000 [00:06<15:15,  1.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  1%|          | 6/1000 [00:07<13:41,  1.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

  1%|          | 7/1000 [00:07<12:29,  1.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  1%|          | 8/1000 [00:08<11:33,  1.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  1%|          | 9/1000 [00:09<10:57,  1.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

  1%|          | 10/1000 [00:09<10:08,  1.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step

  1%|          | 11/1000 [00:10<10:07,  1.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

  1%|          | 12/1000 [00:20<58:42,  3.57s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

  1%|▏         | 13/1000 [00:20<41:39,  2.53s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

  1%|▏         | 14/1000 [00:20<29:55,  1.82s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

  2%|▏         | 15/1000 [00:20<21:32,  1.31s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

  2%|▏         | 16/1000 [00:21<15:44,  1.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

  2%|▏         | 17/1000 [00:21<11:32,  1.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

  2%|▏         | 18/1000 [00:21<08:35,  1.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

  2%|▏         | 19/1000 [00:21<06:32,  2.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

  2%|▏         | 21/1000 [00:21<04:07,  3.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

  2%|▏         | 23/1000 [00:21<03:05,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  2%|▎         | 25/1000 [00:21<02:24,  6.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  3%|▎         | 27/1000 [00:22<02:00,  8.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  3%|▎         | 29/1000 [00:22<01:45,  9.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  3%|▎         | 31/1000 [00:22<01:35, 10.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  3%|▎         | 33/1000 [00:22<01:27, 11.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

  4%|▎         | 35/1000 [00:22<01:23, 11.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  4%|▎         | 37/1000 [00:22<01:21, 11.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

  4%|▍         | 39/1000 [00:23<01:18, 12.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step

  4%|▍         | 41/1000 [00:23<01:15, 12.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  4%|▍         | 43/1000 [00:23<01:13, 12.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

  4%|▍         | 45/1000 [00:23<01:12, 13.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

  5%|▍         | 47/1000 [00:23<01:12, 13.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

  5%|▍         | 49/1000 [00:23<01:11, 13.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

  5%|▌         | 51/1000 [00:23<01:12, 13.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

  5%|▌         | 53/1000 [00:24<01:11, 13.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  6%|▌         | 55/1000 [00:24<01:11, 13.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step

  6%|▌         | 57/1000 [00:24<01:10, 13.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  6%|▌         | 59/1000 [00:24<01:10, 13.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

  6%|▌         | 61/1000 [00:24<01:10, 13.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

  6%|▋         | 63/1000 [00:24<01:11, 13.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  6%|▋         | 65/1000 [00:24<01:12, 12.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

  7%|▋         | 67/1000 [00:25<01:12, 12.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

  7%|▋         | 69/1000 [00:25<01:13, 12.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  7%|▋         | 71/1000 [00:25<01:17, 12.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  7%|▋         | 73/1000 [00:25<01:15, 12.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  8%|▊         | 75/1000 [00:25<01:13, 12.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

  8%|▊         | 77/1000 [00:25<01:14, 12.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

  8%|▊         | 79/1000 [00:26<01:13, 12.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  8%|▊         | 81/1000 [00:26<01:12, 12.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

  8%|▊         | 83/1000 [00:26<01:12, 12.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

  8%|▊         | 85/1000 [00:26<01:12, 12.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

  9%|▊         | 87/1000 [00:26<01:13, 12.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

  9%|▉         | 89/1000 [00:26<01:14, 12.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

  9%|▉         | 91/1000 [00:27<01:15, 12.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

  9%|▉         | 93/1000 [00:27<01:13, 12.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 10%|▉         | 95/1000 [00:27<01:13, 12.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 10%|▉         | 97/1000 [00:27<01:12, 12.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 10%|▉         | 99/1000 [00:27<01:11, 12.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 10%|█         | 101/1000 [00:27<01:12, 12.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 10%|█         | 103/1000 [00:28<01:13, 12.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

 10%|█         | 105/1000 [00:28<01:10, 12.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 11%|█         | 107/1000 [00:28<01:10, 12.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 11%|█         | 109/1000 [00:28<01:11, 12.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 11%|█         | 111/1000 [00:28<01:10, 12.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 11%|█▏        | 113/1000 [00:28<01:09, 12.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 12%|█▏        | 115/1000 [00:28<01:09, 12.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

 12%|█▏        | 117/1000 [00:29<01:09, 12.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 12%|█▏        | 119/1000 [00:29<01:09, 12.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 12%|█▏        | 121/1000 [00:29<01:09, 12.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 12%|█▏        | 123/1000 [00:29<01:14, 11.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 12%|█▎        | 125/1000 [00:29<01:13, 11.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 13%|█▎        | 127/1000 [00:29<01:10, 12.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 13%|█▎        | 129/1000 [00:30<01:10, 12.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 13%|█▎        | 131/1000 [00:30<01:10, 12.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

 13%|█▎        | 133/1000 [00:30<01:16, 11.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step

 14%|█▎        | 135/1000 [00:30<01:40,  8.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 14%|█▎        | 136/1000 [00:30<01:44,  8.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step

 14%|█▎        | 137/1000 [00:31<02:00,  7.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 14%|█▍        | 138/1000 [00:31<01:57,  7.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 14%|█▍        | 139/1000 [00:31<01:51,  7.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

 14%|█▍        | 140/1000 [00:31<02:05,  6.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

 14%|█▍        | 141/1000 [00:31<02:21,  6.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

 14%|█▍        | 142/1000 [00:32<02:31,  5.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

 14%|█▍        | 143/1000 [00:32<03:00,  4.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

 14%|█▍        | 144/1000 [00:32<02:58,  4.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

 14%|█▍        | 145/1000 [00:32<02:52,  4.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

 15%|█▍        | 146/1000 [00:33<03:08,  4.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

 15%|█▍        | 147/1000 [00:33<02:50,  5.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

 15%|█▍        | 148/1000 [00:33<02:52,  4.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

 15%|█▍        | 149/1000 [00:33<02:51,  4.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

 15%|█▌        | 150/1000 [00:33<02:48,  5.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

 15%|█▌        | 151/1000 [00:33<02:41,  5.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

 15%|█▌        | 152/1000 [00:34<03:03,  4.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

 15%|█▌        | 153/1000 [00:34<03:15,  4.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step

 15%|█▌        | 154/1000 [00:34<03:36,  3.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 16%|█▌        | 155/1000 [00:34<03:02,  4.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 16%|█▌        | 156/1000 [00:35<02:36,  5.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 16%|█▌        | 157/1000 [00:35<02:18,  6.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 16%|█▌        | 158/1000 [00:35<02:12,  6.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 16%|█▌        | 159/1000 [00:35<02:08,  6.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step

 16%|█▌        | 160/1000 [00:35<02:04,  6.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 16%|█▌        | 161/1000 [00:35<02:02,  6.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step

 16%|█▌        | 162/1000 [00:35<02:26,  5.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

 16%|█▋        | 163/1000 [00:36<03:09,  4.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

 16%|█▋        | 164/1000 [00:36<03:01,  4.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

 16%|█▋        | 165/1000 [00:36<02:57,  4.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

 17%|█▋        | 166/1000 [00:36<02:53,  4.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

 17%|█▋        | 167/1000 [00:37<03:11,  4.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

 17%|█▋        | 168/1000 [00:37<03:07,  4.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

 17%|█▋        | 169/1000 [00:37<03:20,  4.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step

 17%|█▋        | 170/1000 [00:37<03:03,  4.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

 17%|█▋        | 171/1000 [00:38<02:54,  4.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step

 17%|█▋        | 172/1000 [00:38<02:44,  5.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step

 17%|█▋        | 173/1000 [00:38<02:44,  5.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 17%|█▋        | 174/1000 [00:38<02:23,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 18%|█▊        | 175/1000 [00:38<02:08,  6.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

 18%|█▊        | 176/1000 [00:38<02:03,  6.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 18%|█▊        | 177/1000 [00:38<02:00,  6.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 18%|█▊        | 178/1000 [00:39<01:52,  7.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 18%|█▊        | 179/1000 [00:39<01:51,  7.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

 18%|█▊        | 180/1000 [00:39<01:58,  6.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 18%|█▊        | 182/1000 [00:39<01:32,  8.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 18%|█▊        | 184/1000 [00:39<01:21,  9.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 19%|█▊        | 186/1000 [00:39<01:17, 10.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 19%|█▉        | 188/1000 [00:39<01:14, 10.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

 19%|█▉        | 190/1000 [00:40<01:10, 11.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 19%|█▉        | 192/1000 [00:40<01:12, 11.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 19%|█▉        | 194/1000 [00:40<01:08, 11.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 20%|█▉        | 196/1000 [00:40<01:07, 11.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 20%|█▉        | 198/1000 [00:40<01:06, 12.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 20%|██        | 200/1000 [00:40<01:09, 11.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 20%|██        | 202/1000 [00:41<01:06, 11.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 20%|██        | 204/1000 [00:41<01:05, 12.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 21%|██        | 206/1000 [00:41<01:04, 12.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 21%|██        | 208/1000 [00:41<01:03, 12.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 21%|██        | 210/1000 [00:41<01:02, 12.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

 21%|██        | 212/1000 [00:41<01:02, 12.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

 21%|██▏       | 214/1000 [00:42<01:02, 12.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 22%|██▏       | 216/1000 [00:42<01:06, 11.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 22%|██▏       | 218/1000 [00:42<01:04, 12.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 22%|██▏       | 220/1000 [00:42<01:03, 12.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 22%|██▏       | 222/1000 [00:42<01:02, 12.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 22%|██▏       | 224/1000 [00:42<01:01, 12.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 23%|██▎       | 226/1000 [00:43<01:02, 12.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 23%|██▎       | 228/1000 [00:43<01:01, 12.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 23%|██▎       | 230/1000 [00:43<01:02, 12.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 23%|██▎       | 232/1000 [00:43<01:01, 12.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 23%|██▎       | 234/1000 [00:43<01:01, 12.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 24%|██▎       | 236/1000 [00:43<01:00, 12.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 24%|██▍       | 238/1000 [00:44<01:03, 11.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

 24%|██▍       | 240/1000 [00:44<01:06, 11.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 24%|██▍       | 242/1000 [00:44<01:07, 11.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 24%|██▍       | 244/1000 [00:44<01:06, 11.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 25%|██▍       | 246/1000 [00:44<01:03, 11.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 25%|██▍       | 248/1000 [00:44<01:02, 11.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 25%|██▌       | 250/1000 [00:45<01:02, 11.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 25%|██▌       | 252/1000 [00:45<01:01, 12.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 25%|██▌       | 254/1000 [00:45<01:00, 12.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 26%|██▌       | 256/1000 [00:45<00:59, 12.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 26%|██▌       | 258/1000 [00:45<00:59, 12.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 26%|██▌       | 260/1000 [00:45<00:58, 12.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 26%|██▌       | 262/1000 [00:46<00:57, 12.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 26%|██▋       | 264/1000 [00:46<00:59, 12.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 27%|██▋       | 266/1000 [00:46<00:58, 12.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 27%|██▋       | 268/1000 [00:46<00:57, 12.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 27%|██▋       | 270/1000 [00:46<01:00, 12.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 27%|██▋       | 272/1000 [00:46<00:59, 12.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 27%|██▋       | 274/1000 [00:46<00:58, 12.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 28%|██▊       | 276/1000 [00:47<00:59, 12.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 28%|██▊       | 278/1000 [00:47<00:58, 12.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 28%|██▊       | 280/1000 [00:47<00:58, 12.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 28%|██▊       | 282/1000 [00:47<00:58, 12.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 28%|██▊       | 284/1000 [00:47<00:57, 12.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

 29%|██▊       | 286/1000 [00:47<01:00, 11.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

 29%|██▉       | 288/1000 [00:48<00:59, 11.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 29%|██▉       | 290/1000 [00:48<00:59, 12.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step

 29%|██▉       | 292/1000 [00:48<01:04, 10.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 29%|██▉       | 294/1000 [00:48<01:09, 10.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 30%|██▉       | 296/1000 [00:48<01:12,  9.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 30%|██▉       | 297/1000 [00:49<01:12,  9.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step

 30%|██▉       | 298/1000 [00:49<01:16,  9.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 30%|██▉       | 299/1000 [00:49<01:16,  9.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 30%|███       | 300/1000 [00:49<01:20,  8.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 30%|███       | 301/1000 [00:49<01:24,  8.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 30%|███       | 302/1000 [00:49<01:26,  8.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 30%|███       | 303/1000 [00:49<01:24,  8.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 30%|███       | 304/1000 [00:49<01:27,  7.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 30%|███       | 305/1000 [00:50<01:23,  8.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

 31%|███       | 306/1000 [00:50<01:22,  8.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 31%|███       | 307/1000 [00:50<01:26,  8.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 31%|███       | 308/1000 [00:50<01:31,  7.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 31%|███       | 309/1000 [00:50<01:26,  7.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 31%|███       | 310/1000 [00:50<01:26,  7.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 31%|███       | 311/1000 [00:50<01:24,  8.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 31%|███       | 312/1000 [00:50<01:24,  8.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 31%|███▏      | 313/1000 [00:51<01:26,  7.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 31%|███▏      | 314/1000 [00:51<01:26,  7.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 32%|███▏      | 315/1000 [00:51<01:27,  7.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

 32%|███▏      | 316/1000 [00:51<01:26,  7.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 32%|███▏      | 317/1000 [00:51<01:28,  7.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 32%|███▏      | 318/1000 [00:51<01:26,  7.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 32%|███▏      | 319/1000 [00:51<01:25,  7.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 32%|███▏      | 320/1000 [00:52<01:29,  7.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 32%|███▏      | 321/1000 [00:52<01:25,  7.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 32%|███▏      | 322/1000 [00:52<01:23,  8.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 32%|███▏      | 323/1000 [00:52<01:27,  7.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step

 32%|███▏      | 324/1000 [00:52<01:33,  7.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 32%|███▎      | 325/1000 [00:52<01:33,  7.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 33%|███▎      | 326/1000 [00:52<01:33,  7.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 33%|███▎      | 327/1000 [00:52<01:29,  7.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 33%|███▎      | 328/1000 [00:53<01:28,  7.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 33%|███▎      | 329/1000 [00:53<01:30,  7.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 33%|███▎      | 330/1000 [00:53<01:32,  7.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 33%|███▎      | 331/1000 [00:53<01:29,  7.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 33%|███▎      | 332/1000 [00:53<01:33,  7.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 33%|███▎      | 333/1000 [00:53<01:32,  7.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 33%|███▎      | 334/1000 [00:53<01:26,  7.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 34%|███▎      | 335/1000 [00:53<01:20,  8.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 34%|███▎      | 337/1000 [00:54<01:07,  9.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 34%|███▍      | 339/1000 [00:54<01:01, 10.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 34%|███▍      | 341/1000 [00:54<00:58, 11.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 34%|███▍      | 343/1000 [00:54<00:58, 11.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 34%|███▍      | 345/1000 [00:54<00:56, 11.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 35%|███▍      | 347/1000 [00:54<00:55, 11.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 35%|███▍      | 349/1000 [00:55<00:54, 11.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 35%|███▌      | 351/1000 [00:55<00:59, 10.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 35%|███▌      | 353/1000 [00:55<00:59, 10.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 36%|███▌      | 355/1000 [00:55<01:00, 10.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 36%|███▌      | 357/1000 [00:55<00:57, 11.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 36%|███▌      | 359/1000 [00:56<00:59, 10.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 36%|███▌      | 361/1000 [00:56<00:56, 11.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 36%|███▋      | 363/1000 [00:56<00:55, 11.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 36%|███▋      | 365/1000 [00:56<00:54, 11.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 37%|███▋      | 367/1000 [00:56<00:54, 11.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 37%|███▋      | 369/1000 [00:56<00:53, 11.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 37%|███▋      | 371/1000 [00:57<00:52, 12.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 37%|███▋      | 373/1000 [00:57<00:51, 12.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 38%|███▊      | 375/1000 [00:57<00:50, 12.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 38%|███▊      | 377/1000 [00:57<00:50, 12.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

 38%|███▊      | 379/1000 [00:57<00:53, 11.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 38%|███▊      | 381/1000 [00:57<00:51, 11.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 38%|███▊      | 383/1000 [00:58<00:52, 11.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 38%|███▊      | 385/1000 [00:58<00:51, 11.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 39%|███▊      | 387/1000 [00:58<00:50, 12.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 39%|███▉      | 389/1000 [00:58<00:50, 12.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 39%|███▉      | 391/1000 [00:58<00:50, 12.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 39%|███▉      | 393/1000 [00:58<00:50, 11.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 40%|███▉      | 395/1000 [00:59<00:52, 11.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 40%|███▉      | 397/1000 [00:59<00:51, 11.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 40%|███▉      | 399/1000 [00:59<00:50, 11.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 40%|████      | 401/1000 [00:59<00:50, 11.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 40%|████      | 403/1000 [00:59<00:49, 11.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 40%|████      | 405/1000 [00:59<00:50, 11.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 41%|████      | 407/1000 [01:00<00:50, 11.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 41%|████      | 409/1000 [01:00<00:49, 11.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

 41%|████      | 411/1000 [01:00<00:50, 11.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 41%|████▏     | 413/1000 [01:00<00:52, 11.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 42%|████▏     | 415/1000 [01:00<00:51, 11.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 42%|████▏     | 417/1000 [01:01<00:54, 10.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 42%|████▏     | 419/1000 [01:01<00:52, 11.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 42%|████▏     | 421/1000 [01:01<00:50, 11.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 42%|████▏     | 423/1000 [01:01<00:50, 11.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 42%|████▎     | 425/1000 [01:01<00:51, 11.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 43%|████▎     | 427/1000 [01:01<00:50, 11.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 43%|████▎     | 429/1000 [01:02<00:50, 11.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 43%|████▎     | 431/1000 [01:02<00:48, 11.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 43%|████▎     | 433/1000 [01:02<00:48, 11.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 44%|████▎     | 435/1000 [01:02<00:47, 11.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 44%|████▎     | 437/1000 [01:02<00:47, 11.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 44%|████▍     | 439/1000 [01:02<00:46, 12.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 44%|████▍     | 441/1000 [01:03<00:46, 11.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 44%|████▍     | 443/1000 [01:03<00:46, 11.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 44%|████▍     | 445/1000 [01:03<00:46, 11.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 45%|████▍     | 447/1000 [01:03<00:46, 11.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 45%|████▍     | 449/1000 [01:03<00:48, 11.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 45%|████▌     | 451/1000 [01:03<00:47, 11.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step

 45%|████▌     | 453/1000 [01:04<00:54, 10.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

 46%|████▌     | 455/1000 [01:04<00:57,  9.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 46%|████▌     | 456/1000 [01:04<00:58,  9.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 46%|████▌     | 457/1000 [01:04<01:01,  8.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

 46%|████▌     | 458/1000 [01:04<01:03,  8.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 46%|████▌     | 459/1000 [01:04<01:03,  8.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 46%|████▌     | 460/1000 [01:05<01:01,  8.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 46%|████▌     | 461/1000 [01:05<01:04,  8.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 46%|████▌     | 462/1000 [01:05<01:03,  8.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 46%|████▋     | 463/1000 [01:05<01:03,  8.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 46%|████▋     | 464/1000 [01:05<01:02,  8.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 46%|████▋     | 465/1000 [01:05<01:02,  8.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 47%|████▋     | 466/1000 [01:05<01:04,  8.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 47%|████▋     | 467/1000 [01:05<01:03,  8.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 47%|████▋     | 468/1000 [01:05<01:02,  8.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 47%|████▋     | 469/1000 [01:06<01:05,  8.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 47%|████▋     | 470/1000 [01:06<01:09,  7.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 47%|████▋     | 471/1000 [01:06<01:05,  8.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 47%|████▋     | 472/1000 [01:06<01:03,  8.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 47%|████▋     | 473/1000 [01:06<01:01,  8.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 47%|████▋     | 474/1000 [01:06<01:03,  8.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

 48%|████▊     | 475/1000 [01:06<01:05,  8.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 48%|████▊     | 476/1000 [01:06<01:04,  8.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 48%|████▊     | 477/1000 [01:07<01:05,  7.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

 48%|████▊     | 478/1000 [01:07<01:05,  7.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 48%|████▊     | 479/1000 [01:07<01:05,  7.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 48%|████▊     | 480/1000 [01:07<01:07,  7.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 48%|████▊     | 481/1000 [01:07<01:06,  7.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 48%|████▊     | 482/1000 [01:07<01:05,  7.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 48%|████▊     | 483/1000 [01:07<01:08,  7.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 48%|████▊     | 484/1000 [01:08<01:10,  7.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 48%|████▊     | 485/1000 [01:08<01:07,  7.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

 49%|████▊     | 486/1000 [01:08<01:06,  7.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 49%|████▊     | 487/1000 [01:08<01:04,  7.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 49%|████▉     | 488/1000 [01:08<01:01,  8.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 49%|████▉     | 489/1000 [01:08<01:04,  7.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 49%|████▉     | 490/1000 [01:08<01:05,  7.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 49%|████▉     | 491/1000 [01:08<01:06,  7.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 49%|████▉     | 492/1000 [01:09<01:08,  7.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 49%|████▉     | 493/1000 [01:09<01:06,  7.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step

 49%|████▉     | 494/1000 [01:09<01:07,  7.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

 50%|████▉     | 495/1000 [01:09<01:08,  7.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 50%|████▉     | 496/1000 [01:09<01:09,  7.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 50%|████▉     | 498/1000 [01:09<00:58,  8.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 50%|█████     | 500/1000 [01:09<00:50,  9.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 50%|█████     | 501/1000 [01:10<00:52,  9.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 50%|█████     | 502/1000 [01:10<00:52,  9.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 50%|█████     | 504/1000 [01:10<00:47, 10.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

 51%|█████     | 506/1000 [01:10<00:49, 10.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 51%|█████     | 508/1000 [01:10<00:46, 10.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 51%|█████     | 510/1000 [01:10<00:46, 10.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 51%|█████     | 512/1000 [01:11<00:43, 11.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 51%|█████▏    | 514/1000 [01:11<00:41, 11.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

 52%|█████▏    | 516/1000 [01:11<00:43, 11.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 52%|█████▏    | 518/1000 [01:11<00:43, 11.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 52%|█████▏    | 520/1000 [01:11<00:42, 11.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 52%|█████▏    | 522/1000 [01:11<00:41, 11.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 52%|█████▏    | 524/1000 [01:12<00:39, 11.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 53%|█████▎    | 526/1000 [01:12<00:41, 11.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

 53%|█████▎    | 528/1000 [01:12<00:42, 11.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 53%|█████▎    | 530/1000 [01:12<00:41, 11.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 53%|█████▎    | 532/1000 [01:12<00:41, 11.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 53%|█████▎    | 534/1000 [01:13<00:44, 10.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 54%|█████▎    | 536/1000 [01:13<00:42, 11.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 54%|█████▍    | 538/1000 [01:13<00:42, 10.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

 54%|█████▍    | 540/1000 [01:13<00:42, 10.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 54%|█████▍    | 542/1000 [01:13<00:41, 11.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 54%|█████▍    | 544/1000 [01:13<00:42, 10.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 55%|█████▍    | 546/1000 [01:14<00:42, 10.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 55%|█████▍    | 548/1000 [01:14<00:40, 11.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 55%|█████▌    | 550/1000 [01:14<00:39, 11.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 55%|█████▌    | 552/1000 [01:14<00:39, 11.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 55%|█████▌    | 554/1000 [01:14<00:40, 10.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 56%|█████▌    | 556/1000 [01:15<00:40, 10.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 56%|█████▌    | 558/1000 [01:15<00:41, 10.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 56%|█████▌    | 560/1000 [01:15<00:39, 11.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

 56%|█████▌    | 562/1000 [01:15<00:38, 11.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

 56%|█████▋    | 564/1000 [01:15<00:39, 11.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 57%|█████▋    | 566/1000 [01:15<00:38, 11.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 57%|█████▋    | 568/1000 [01:16<00:37, 11.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 57%|█████▋    | 570/1000 [01:16<00:38, 11.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 57%|█████▋    | 572/1000 [01:16<00:38, 11.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 57%|█████▋    | 574/1000 [01:16<00:37, 11.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 58%|█████▊    | 576/1000 [01:16<00:37, 11.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 58%|█████▊    | 578/1000 [01:16<00:36, 11.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 58%|█████▊    | 580/1000 [01:17<00:37, 11.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 58%|█████▊    | 582/1000 [01:17<00:37, 11.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 58%|█████▊    | 584/1000 [01:17<00:36, 11.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

 59%|█████▊    | 586/1000 [01:17<00:39, 10.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 59%|█████▉    | 588/1000 [01:17<00:41, 10.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 59%|█████▉    | 590/1000 [01:18<00:38, 10.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 59%|█████▉    | 592/1000 [01:18<00:36, 11.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 59%|█████▉    | 594/1000 [01:18<00:38, 10.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

 60%|█████▉    | 596/1000 [01:19<01:15,  5.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 60%|█████▉    | 597/1000 [01:19<01:16,  5.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

 60%|█████▉    | 598/1000 [01:19<01:19,  5.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

 60%|█████▉    | 599/1000 [01:20<01:51,  3.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 266ms/step

 60%|██████    | 600/1000 [01:20<02:15,  2.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step

 60%|██████    | 601/1000 [01:21<02:30,  2.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step

 60%|██████    | 602/1000 [01:21<02:39,  2.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step

 60%|██████    | 603/1000 [01:22<02:45,  2.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step

 60%|██████    | 604/1000 [01:22<02:46,  2.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 60%|██████    | 605/1000 [01:22<02:10,  3.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 61%|██████    | 606/1000 [01:22<01:45,  3.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 61%|██████    | 607/1000 [01:22<01:26,  4.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step

 61%|██████    | 608/1000 [01:23<01:16,  5.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

 61%|██████    | 609/1000 [01:23<01:09,  5.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 61%|██████    | 610/1000 [01:23<01:01,  6.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 61%|██████    | 611/1000 [01:23<00:57,  6.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

 61%|██████    | 612/1000 [01:23<00:57,  6.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 61%|██████▏   | 613/1000 [01:23<00:55,  7.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 61%|██████▏   | 614/1000 [01:23<00:53,  7.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step

 62%|██████▏   | 615/1000 [01:24<00:53,  7.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 62%|██████▏   | 616/1000 [01:24<00:52,  7.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 62%|██████▏   | 617/1000 [01:24<00:49,  7.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 62%|██████▏   | 619/1000 [01:24<00:40,  9.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 62%|██████▏   | 621/1000 [01:24<00:39,  9.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 62%|██████▏   | 622/1000 [01:24<00:39,  9.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 62%|██████▏   | 624/1000 [01:24<00:38,  9.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 63%|██████▎   | 626/1000 [01:25<00:35, 10.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 63%|██████▎   | 628/1000 [01:25<00:35, 10.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 63%|██████▎   | 630/1000 [01:25<00:33, 10.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 63%|██████▎   | 632/1000 [01:25<00:32, 11.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 63%|██████▎   | 634/1000 [01:25<00:31, 11.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 64%|██████▎   | 636/1000 [01:25<00:31, 11.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 64%|██████▍   | 638/1000 [01:26<00:32, 11.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 64%|██████▍   | 640/1000 [01:26<00:33, 10.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 64%|██████▍   | 642/1000 [01:26<00:33, 10.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 64%|██████▍   | 644/1000 [01:26<00:32, 11.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 65%|██████▍   | 646/1000 [01:26<00:32, 10.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 65%|██████▍   | 648/1000 [01:27<00:32, 10.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 65%|██████▌   | 650/1000 [01:27<00:31, 11.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 65%|██████▌   | 652/1000 [01:27<00:33, 10.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 65%|██████▌   | 654/1000 [01:27<00:33, 10.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 66%|██████▌   | 656/1000 [01:27<00:31, 10.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

 66%|██████▌   | 658/1000 [01:28<00:30, 11.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 66%|██████▌   | 660/1000 [01:28<00:31, 10.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 66%|██████▌   | 662/1000 [01:28<00:32, 10.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 66%|██████▋   | 664/1000 [01:28<00:31, 10.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 67%|██████▋   | 666/1000 [01:28<00:31, 10.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 67%|██████▋   | 668/1000 [01:28<00:30, 10.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

 67%|██████▋   | 670/1000 [01:29<00:29, 11.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 67%|██████▋   | 672/1000 [01:29<00:28, 11.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 67%|██████▋   | 674/1000 [01:29<00:29, 10.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

 68%|██████▊   | 676/1000 [01:29<00:29, 11.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 68%|██████▊   | 678/1000 [01:29<00:29, 10.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 68%|██████▊   | 680/1000 [01:30<00:28, 11.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 68%|██████▊   | 682/1000 [01:30<00:30, 10.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

 68%|██████▊   | 684/1000 [01:30<00:29, 10.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 69%|██████▊   | 686/1000 [01:30<00:29, 10.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 69%|██████▉   | 688/1000 [01:30<00:29, 10.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 69%|██████▉   | 690/1000 [01:30<00:28, 11.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 69%|██████▉   | 692/1000 [01:31<00:29, 10.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 69%|██████▉   | 694/1000 [01:31<00:29, 10.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step

 70%|██████▉   | 696/1000 [01:31<00:48,  6.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

 70%|██████▉   | 697/1000 [01:32<00:56,  5.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step

 70%|██████▉   | 698/1000 [01:32<01:06,  4.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

 70%|██████▉   | 699/1000 [01:32<01:14,  4.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

 70%|███████   | 700/1000 [01:33<01:17,  3.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

 70%|███████   | 701/1000 [01:33<01:25,  3.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

 70%|███████   | 702/1000 [01:33<01:23,  3.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

 70%|███████   | 703/1000 [01:34<01:28,  3.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

 70%|███████   | 704/1000 [01:34<01:37,  3.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

 70%|███████   | 705/1000 [01:34<01:21,  3.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

 71%|███████   | 706/1000 [01:34<01:08,  4.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 71%|███████   | 707/1000 [01:35<00:59,  4.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 71%|███████   | 708/1000 [01:35<00:53,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 71%|███████   | 709/1000 [01:35<00:48,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

 71%|███████   | 710/1000 [01:35<00:46,  6.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

 71%|███████   | 711/1000 [01:35<00:45,  6.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 71%|███████   | 712/1000 [01:35<00:44,  6.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 71%|███████▏  | 713/1000 [01:35<00:44,  6.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 71%|███████▏  | 714/1000 [01:36<00:42,  6.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 72%|███████▏  | 715/1000 [01:36<00:39,  7.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 72%|███████▏  | 716/1000 [01:36<00:39,  7.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

 72%|███████▏  | 717/1000 [01:36<00:48,  5.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

 72%|███████▏  | 718/1000 [01:36<01:05,  4.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

 72%|███████▏  | 719/1000 [01:37<00:57,  4.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step

 72%|███████▏  | 720/1000 [01:37<01:12,  3.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

 72%|███████▏  | 721/1000 [01:37<01:13,  3.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 72%|███████▏  | 722/1000 [01:37<01:02,  4.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

 72%|███████▏  | 723/1000 [01:38<01:01,  4.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 72%|███████▏  | 724/1000 [01:38<00:53,  5.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

 72%|███████▎  | 725/1000 [01:38<00:55,  4.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

 73%|███████▎  | 726/1000 [01:38<01:03,  4.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

 73%|███████▎  | 727/1000 [01:38<01:04,  4.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 73%|███████▎  | 728/1000 [01:39<00:57,  4.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

 73%|███████▎  | 729/1000 [01:39<00:55,  4.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 73%|███████▎  | 730/1000 [01:39<00:47,  5.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 73%|███████▎  | 731/1000 [01:39<00:43,  6.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

 73%|███████▎  | 732/1000 [01:39<00:48,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

 73%|███████▎  | 733/1000 [01:40<00:51,  5.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step

 73%|███████▎  | 734/1000 [01:40<00:55,  4.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 74%|███████▎  | 735/1000 [01:40<00:50,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

 74%|███████▎  | 736/1000 [01:40<00:47,  5.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

 74%|███████▎  | 737/1000 [01:40<00:51,  5.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 74%|███████▍  | 738/1000 [01:40<00:46,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 74%|███████▍  | 739/1000 [01:41<00:42,  6.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 74%|███████▍  | 740/1000 [01:41<00:40,  6.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 74%|███████▍  | 741/1000 [01:41<00:39,  6.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 74%|███████▍  | 742/1000 [01:41<00:37,  6.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

 74%|███████▍  | 743/1000 [01:41<00:36,  7.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

 74%|███████▍  | 744/1000 [01:41<00:39,  6.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step

 74%|███████▍  | 745/1000 [01:41<00:37,  6.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 75%|███████▍  | 746/1000 [01:42<00:36,  6.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 75%|███████▍  | 747/1000 [01:42<00:36,  6.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 75%|███████▍  | 748/1000 [01:42<00:35,  7.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step

 75%|███████▍  | 749/1000 [01:42<00:36,  6.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 75%|███████▌  | 750/1000 [01:42<00:35,  7.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 75%|███████▌  | 751/1000 [01:42<00:34,  7.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 75%|███████▌  | 752/1000 [01:42<00:34,  7.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

 75%|███████▌  | 753/1000 [01:43<00:32,  7.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 76%|███████▌  | 755/1000 [01:43<00:27,  8.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step

 76%|███████▌  | 756/1000 [01:43<00:31,  7.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 76%|███████▌  | 757/1000 [01:43<00:31,  7.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 76%|███████▌  | 758/1000 [01:43<00:31,  7.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 76%|███████▌  | 759/1000 [01:43<00:32,  7.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 76%|███████▌  | 760/1000 [01:43<00:31,  7.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

 76%|███████▌  | 761/1000 [01:44<00:31,  7.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 76%|███████▌  | 762/1000 [01:44<00:30,  7.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 76%|███████▋  | 763/1000 [01:44<00:30,  7.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 76%|███████▋  | 764/1000 [01:44<00:32,  7.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 76%|███████▋  | 765/1000 [01:44<00:32,  7.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 77%|███████▋  | 766/1000 [01:44<00:29,  7.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 77%|███████▋  | 767/1000 [01:44<00:33,  6.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

 77%|███████▋  | 768/1000 [01:45<00:32,  7.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

 77%|███████▋  | 769/1000 [01:45<00:31,  7.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 77%|███████▋  | 770/1000 [01:45<00:32,  7.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

 77%|███████▋  | 771/1000 [01:45<00:31,  7.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 77%|███████▋  | 772/1000 [01:45<00:31,  7.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

 77%|███████▋  | 773/1000 [01:45<00:31,  7.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 78%|███████▊  | 775/1000 [01:45<00:26,  8.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

 78%|███████▊  | 776/1000 [01:46<00:31,  7.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 78%|███████▊  | 777/1000 [01:46<00:30,  7.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 78%|███████▊  | 778/1000 [01:46<00:30,  7.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 78%|███████▊  | 779/1000 [01:46<00:32,  6.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 78%|███████▊  | 780/1000 [01:46<00:31,  6.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 78%|███████▊  | 781/1000 [01:46<00:29,  7.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 78%|███████▊  | 782/1000 [01:46<00:29,  7.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 78%|███████▊  | 783/1000 [01:47<00:28,  7.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 78%|███████▊  | 784/1000 [01:47<00:28,  7.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 78%|███████▊  | 785/1000 [01:47<00:28,  7.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 79%|███████▊  | 786/1000 [01:47<00:29,  7.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 79%|███████▊  | 787/1000 [01:47<00:30,  6.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 79%|███████▉  | 788/1000 [01:47<00:29,  7.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 79%|███████▉  | 789/1000 [01:47<00:28,  7.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 79%|███████▉  | 790/1000 [01:48<00:28,  7.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step

 79%|███████▉  | 791/1000 [01:48<00:29,  7.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 79%|███████▉  | 792/1000 [01:48<00:30,  6.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

 79%|███████▉  | 793/1000 [01:48<00:34,  6.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

 79%|███████▉  | 794/1000 [01:48<00:41,  5.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step

 80%|███████▉  | 795/1000 [01:49<01:04,  3.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

 80%|███████▉  | 796/1000 [01:49<01:02,  3.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 80%|███████▉  | 797/1000 [01:49<00:52,  3.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 80%|███████▉  | 798/1000 [01:49<00:45,  4.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 80%|███████▉  | 799/1000 [01:50<00:38,  5.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 80%|████████  | 800/1000 [01:50<00:34,  5.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 80%|████████  | 801/1000 [01:50<00:32,  6.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 80%|████████  | 802/1000 [01:50<00:28,  6.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

 80%|████████  | 803/1000 [01:50<00:26,  7.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 80%|████████  | 804/1000 [01:50<00:26,  7.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step

 80%|████████  | 805/1000 [01:50<00:27,  7.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 81%|████████  | 806/1000 [01:50<00:26,  7.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 81%|████████  | 807/1000 [01:51<00:25,  7.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 81%|████████  | 808/1000 [01:51<00:25,  7.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 81%|████████  | 809/1000 [01:51<00:24,  7.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

 81%|████████  | 810/1000 [01:51<00:28,  6.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

 81%|████████  | 811/1000 [01:51<00:32,  5.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step

 81%|████████  | 812/1000 [01:52<00:40,  4.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

 81%|████████▏ | 813/1000 [01:52<00:48,  3.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

 81%|████████▏ | 814/1000 [01:52<00:52,  3.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 82%|████████▏ | 815/1000 [01:52<00:46,  3.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 82%|████████▏ | 816/1000 [01:53<00:41,  4.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

 82%|████████▏ | 817/1000 [01:53<00:35,  5.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 82%|████████▏ | 818/1000 [01:53<00:32,  5.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

 82%|████████▏ | 819/1000 [01:53<00:31,  5.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

 82%|████████▏ | 820/1000 [01:53<00:35,  5.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

 82%|████████▏ | 821/1000 [01:53<00:34,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 82%|████████▏ | 822/1000 [01:54<00:33,  5.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 82%|████████▏ | 823/1000 [01:54<00:29,  5.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 82%|████████▏ | 824/1000 [01:54<00:28,  6.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 82%|████████▎ | 825/1000 [01:54<00:26,  6.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 83%|████████▎ | 826/1000 [01:54<00:26,  6.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 83%|████████▎ | 827/1000 [01:54<00:26,  6.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step

 83%|████████▎ | 828/1000 [01:55<00:25,  6.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

 83%|████████▎ | 829/1000 [01:55<00:26,  6.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step

 83%|████████▎ | 830/1000 [01:55<00:30,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

 83%|████████▎ | 831/1000 [01:55<00:36,  4.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

 83%|████████▎ | 832/1000 [01:55<00:37,  4.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

 83%|████████▎ | 833/1000 [01:56<00:34,  4.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 83%|████████▎ | 834/1000 [01:56<00:30,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

 84%|████████▎ | 835/1000 [01:56<00:31,  5.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 84%|████████▎ | 836/1000 [01:56<00:29,  5.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 84%|████████▎ | 837/1000 [01:56<00:26,  6.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 84%|████████▍ | 838/1000 [01:56<00:25,  6.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step

 84%|████████▍ | 839/1000 [01:57<00:28,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step

 84%|████████▍ | 840/1000 [01:57<00:27,  5.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 84%|████████▍ | 841/1000 [01:57<00:26,  5.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 84%|████████▍ | 842/1000 [01:57<00:25,  6.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

 84%|████████▍ | 843/1000 [01:57<00:23,  6.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

 84%|████████▍ | 844/1000 [01:57<00:25,  6.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 84%|████████▍ | 845/1000 [01:58<00:23,  6.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

 85%|████████▍ | 846/1000 [01:58<00:22,  6.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 85%|████████▍ | 847/1000 [01:58<00:22,  6.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 85%|████████▍ | 848/1000 [01:58<00:22,  6.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

 85%|████████▍ | 849/1000 [01:58<00:23,  6.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

 85%|████████▌ | 850/1000 [01:58<00:22,  6.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

 85%|████████▌ | 852/1000 [01:58<00:18,  7.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step

 85%|████████▌ | 853/1000 [01:59<00:19,  7.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

 85%|████████▌ | 854/1000 [01:59<00:22,  6.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 86%|████████▌ | 855/1000 [01:59<00:23,  6.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

 86%|████████▌ | 856/1000 [01:59<00:22,  6.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 86%|████████▌ | 857/1000 [01:59<00:21,  6.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 86%|████████▌ | 858/1000 [01:59<00:20,  6.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 86%|████████▌ | 859/1000 [02:00<00:20,  7.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step

 86%|████████▌ | 860/1000 [02:00<00:19,  7.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 86%|████████▌ | 861/1000 [02:00<00:19,  7.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step

 86%|████████▌ | 862/1000 [02:00<00:19,  7.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

 86%|████████▋ | 863/1000 [02:00<00:19,  6.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 86%|████████▋ | 864/1000 [02:00<00:19,  6.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 86%|████████▋ | 865/1000 [02:00<00:18,  7.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 87%|████████▋ | 866/1000 [02:01<00:19,  7.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

 87%|████████▋ | 867/1000 [02:01<00:20,  6.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 87%|████████▋ | 868/1000 [02:01<00:19,  6.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 87%|████████▋ | 869/1000 [02:01<00:19,  6.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 87%|████████▋ | 870/1000 [02:01<00:19,  6.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 87%|████████▋ | 871/1000 [02:01<00:19,  6.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 87%|████████▋ | 872/1000 [02:01<00:18,  6.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 87%|████████▋ | 873/1000 [02:02<00:18,  6.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step

 87%|████████▋ | 874/1000 [02:02<00:19,  6.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step

 88%|████████▊ | 875/1000 [02:02<00:19,  6.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step

 88%|████████▊ | 876/1000 [02:02<00:19,  6.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

 88%|████████▊ | 877/1000 [02:02<00:18,  6.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

 88%|████████▊ | 878/1000 [02:02<00:18,  6.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

 88%|████████▊ | 879/1000 [02:03<00:19,  6.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

 88%|████████▊ | 880/1000 [02:03<00:23,  5.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

 88%|████████▊ | 881/1000 [02:03<00:24,  4.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

 88%|████████▊ | 882/1000 [02:03<00:25,  4.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

 88%|████████▊ | 883/1000 [02:04<00:24,  4.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

 88%|████████▊ | 884/1000 [02:04<00:27,  4.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

 88%|████████▊ | 885/1000 [02:04<00:29,  3.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

 89%|████████▊ | 886/1000 [02:04<00:27,  4.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

 89%|████████▊ | 887/1000 [02:04<00:23,  4.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step

 89%|████████▉ | 888/1000 [02:05<00:22,  5.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 89%|████████▉ | 889/1000 [02:05<00:20,  5.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step

 89%|████████▉ | 890/1000 [02:05<00:19,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 89%|████████▉ | 891/1000 [02:05<00:18,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

 89%|████████▉ | 892/1000 [02:05<00:17,  6.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 89%|████████▉ | 893/1000 [02:05<00:16,  6.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 89%|████████▉ | 894/1000 [02:06<00:15,  6.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

 90%|████████▉ | 895/1000 [02:06<00:14,  7.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 90%|████████▉ | 896/1000 [02:06<00:13,  7.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step

 90%|████████▉ | 897/1000 [02:06<00:14,  7.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step

 90%|████████▉ | 898/1000 [02:06<00:15,  6.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 90%|████████▉ | 899/1000 [02:06<00:15,  6.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

 90%|█████████ | 900/1000 [02:06<00:18,  5.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

 90%|█████████ | 901/1000 [02:07<00:19,  5.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step

 90%|█████████ | 902/1000 [02:07<00:19,  5.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

 90%|█████████ | 903/1000 [02:07<00:20,  4.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 90%|█████████ | 904/1000 [02:07<00:18,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

 90%|█████████ | 905/1000 [02:07<00:16,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

 91%|█████████ | 906/1000 [02:08<00:15,  6.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 91%|█████████ | 907/1000 [02:08<00:15,  6.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

 91%|█████████ | 908/1000 [02:08<00:14,  6.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 91%|█████████ | 909/1000 [02:08<00:13,  6.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

 91%|█████████ | 910/1000 [02:08<00:13,  6.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

 91%|█████████ | 911/1000 [02:09<00:19,  4.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

 91%|█████████ | 912/1000 [02:09<00:19,  4.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

 91%|█████████▏| 913/1000 [02:09<00:18,  4.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

 91%|█████████▏| 914/1000 [02:09<00:18,  4.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 92%|█████████▏| 915/1000 [02:09<00:17,  4.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step

 92%|█████████▏| 916/1000 [02:10<00:19,  4.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

 92%|█████████▏| 917/1000 [02:10<00:23,  3.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

 92%|█████████▏| 918/1000 [02:10<00:21,  3.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 92%|█████████▏| 919/1000 [02:10<00:18,  4.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 92%|█████████▏| 920/1000 [02:11<00:15,  5.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 92%|█████████▏| 921/1000 [02:11<00:13,  5.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

 92%|█████████▏| 922/1000 [02:11<00:12,  6.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 92%|█████████▏| 923/1000 [02:11<00:12,  6.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step

 92%|█████████▏| 924/1000 [02:11<00:11,  6.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

 92%|█████████▎| 925/1000 [02:11<00:11,  6.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

 93%|█████████▎| 926/1000 [02:11<00:12,  5.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

 93%|█████████▎| 927/1000 [02:12<00:13,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

 93%|█████████▎| 928/1000 [02:12<00:11,  6.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

 93%|█████████▎| 930/1000 [02:12<00:09,  7.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

 93%|█████████▎| 931/1000 [02:12<00:08,  7.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

 93%|█████████▎| 932/1000 [02:12<00:09,  7.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

 93%|█████████▎| 933/1000 [02:12<00:09,  7.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 93%|█████████▎| 934/1000 [02:13<00:09,  7.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

 94%|█████████▎| 935/1000 [02:13<00:08,  7.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

 94%|█████████▎| 936/1000 [02:13<00:08,  7.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

 94%|█████████▎| 937/1000 [02:13<00:09,  6.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 94%|█████████▍| 938/1000 [02:13<00:09,  6.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

 94%|█████████▍| 939/1000 [02:13<00:09,  6.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

 94%|█████████▍| 940/1000 [02:14<00:11,  5.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

 94%|█████████▍| 941/1000 [02:14<00:13,  4.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

 94%|█████████▍| 942/1000 [02:14<00:13,  4.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

 94%|█████████▍| 943/1000 [02:14<00:13,  4.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

 94%|█████████▍| 944/1000 [02:15<00:13,  4.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

 94%|█████████▍| 945/1000 [02:15<00:12,  4.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

 95%|█████████▍| 946/1000 [02:15<00:13,  4.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

 95%|█████████▍| 947/1000 [02:15<00:14,  3.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 95%|█████████▍| 948/1000 [02:16<00:12,  4.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 95%|█████████▍| 949/1000 [02:16<00:10,  4.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

 95%|█████████▌| 950/1000 [02:16<00:09,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

 95%|█████████▌| 951/1000 [02:16<00:08,  5.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 95%|█████████▌| 952/1000 [02:16<00:07,  6.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

 95%|█████████▌| 953/1000 [02:16<00:07,  6.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

 95%|█████████▌| 954/1000 [02:16<00:06,  6.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

 96%|█████████▌| 955/1000 [02:17<00:06,  6.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step

 96%|█████████▌| 956/1000 [02:17<00:06,  7.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step

 96%|█████████▌| 957/1000 [02:17<00:07,  5.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 96%|█████████▌| 959/1000 [02:17<00:05,  7.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 96%|█████████▌| 960/1000 [02:17<00:05,  7.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

 96%|█████████▌| 961/1000 [02:17<00:05,  7.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

 96%|█████████▌| 962/1000 [02:17<00:04,  7.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step

 96%|█████████▋| 963/1000 [02:18<00:04,  7.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 96%|█████████▋| 964/1000 [02:18<00:04,  8.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

 96%|█████████▋| 965/1000 [02:18<00:04,  8.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

 97%|█████████▋| 966/1000 [02:18<00:04,  8.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

 97%|█████████▋| 967/1000 [02:18<00:04,  7.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

 97%|█████████▋| 968/1000 [02:18<00:04,  7.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

 97%|█████████▋| 969/1000 [02:18<00:04,  7.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step

 97%|█████████▋| 970/1000 [02:18<00:04,  7.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

 97%|█████████▋| 971/1000 [02:19<00:05,  5.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

 97%|█████████▋| 972/1000 [02:19<00:05,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

 97%|█████████▋| 973/1000 [02:19<00:05,  4.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

 97%|█████████▋| 974/1000 [02:20<00:06,  4.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

 98%|█████████▊| 975/1000 [02:20<00:06,  3.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

 98%|█████████▊| 976/1000 [02:20<00:06,  3.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

 98%|█████████▊| 977/1000 [02:20<00:05,  4.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step

 98%|█████████▊| 978/1000 [02:21<00:05,  4.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

 98%|█████████▊| 979/1000 [02:21<00:04,  4.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

 98%|█████████▊| 980/1000 [02:21<00:04,  4.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

 98%|█████████▊| 981/1000 [02:21<00:04,  4.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step

 98%|█████████▊| 982/1000 [02:21<00:03,  4.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

 98%|█████████▊| 983/1000 [02:22<00:04,  4.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step

 98%|█████████▊| 984/1000 [02:22<00:03,  4.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

 98%|█████████▊| 985/1000 [02:22<00:03,  4.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

 99%|█████████▊| 987/1000 [02:22<00:01,  6.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 99%|█████████▉| 989/1000 [02:22<00:01,  7.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

 99%|█████████▉| 991/1000 [02:23<00:01,  8.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

 99%|█████████▉| 993/1000 [02:23<00:00,  9.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

100%|█████████▉| 995/1000 [02:23<00:00,  9.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

100%|█████████▉| 997/1000 [02:23<00:00,  9.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

100%|█████████▉| 999/1000 [02:23<00:00, 10.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

100%|██████████| 1000/1000 [02:23<00:00,  6.95it/s]

Shape of image features: (1000, 512)

In [ ]:
text_features[0].shape

(768,)

In [ ]:
X_text = np.array(text_features)
X_img = np.array(image_features)

X = np.concatenate([X_text, X_img], axis=1)  # shape: (n_samples, 384+512=896)
y = df_train['price'].values

In [14]:
X = np.array(text_features)
# X_img = np.array(image_features)

# X = np.concatenate([X_text, X_img], axis=1)  # shape: (n_samples, 384+512=896)
y = df_train['price'].values

In [11]:
def smape(y_true, y_pred):
    """
    Symmetric Mean Absolute Percentage Error
    Works as a custom loss function for regression.
    """
    epsilon = 1e-6  # to avoid division by zero
    numerator = tf.abs(y_true - y_pred)
    denominator = (tf.abs(y_true) + tf.abs(y_pred) + epsilon) / 2.0
    smape_value = 100 * tf.reduce_mean(numerator / denominator)
    return smape_value

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization,Input

model = Sequential([
    Input(shape=(X.shape[1],)),
    Dense(2000, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(1024, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(752, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(512, activation='relu'),
    BatchNormalization(),
    Dropout(0.5) ,
    Dense(256, activation='relu'),
    BatchNormalization(),

    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(1,activation='linear')   # output: predicted price
])

model.compile(optimizer='adam', loss='mse',metrics=['mae',smape])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2000)           │       770,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 2000)           │         8,000 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1024)           │     2,049,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 752)            │       770,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 752)            │         3,008 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 752)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 512)            │       385,536 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 512)            │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,166,081 (15.89 MB)

 Trainable params: 4,156,993 (15.86 MB)

 Non-trainable params: 9,088 (35.50 KB)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization,Input

model = Sequential([
    Input(shape=(X.shape[1],)),
    Dense(2000, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(1024, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(752, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(512, activation='relu'),
    BatchNormalization(),
    Dropout(0.5) ,
    Dense(256, activation='relu'),
    BatchNormalization(),

    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(1,activation='linear')   # output: predicted price
])

model.compile(optimizer='adam', loss=smape,metrics=['mae', 'mse'])
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_50 (Dense)                │ (None, 2000)           │     4,098,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_34          │ (None, 2000)           │         8,000 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_25 (Dropout)            │ (None, 2000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_51 (Dense)                │ (None, 1024)           │     2,049,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_35          │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_26 (Dropout)            │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_52 (Dense)                │ (None, 752)            │       770,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_36          │ (None, 752)            │         3,008 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_27 (Dropout)            │ (None, 752)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_53 (Dense)                │ (None, 512)            │       385,536 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_37          │ (None, 512)            │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_28 (Dropout)            │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_54 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_38          │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_55 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_56 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_57 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,494,081 (28.59 MB)

 Trainable params: 7,484,993 (28.55 MB)

 Non-trainable params: 9,088 (35.50 KB)

In [15]:
model.fit(X, y, epochs=50, batch_size=16, validation_split=0.2)

Epoch 1/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - loss: 1115.7596 - mae: 17.3552 - smape: 81.9893 - val_loss: 865.4344 - val_mae: 15.6313 - val_smape: 78.4063
Epoch 2/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 917.6603 - mae: 16.1940 - smape: 80.4840 - val_loss: 1324.0302 - val_mae: 17.5149 - val_smape: 81.1144
Epoch 3/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 873.2487 - mae: 15.8647 - smape: 80.3312 - val_loss: 1284.6367 - val_mae: 16.6061 - val_smape: 81.5739
Epoch 4/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 21s 5ms/step - loss: 867.2725 - mae: 15.6441 - smape: 80.3674 - val_loss: 2245.9736 - val_mae: 17.1185 - val_smape: 78.0158
Epoch 5/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 762.8307 - mae: 15.2989 - smape: 80.0540 - val_loss: 1438.5797 - val_mae: 16.6065 - val_smape: 80.2624
Epoch 6/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 864.4496 - mae: 15.2883 - smape: 80.0858 - val_loss: 1524.3580 - val_mae: 17.2864 - val_smape: 80.9090
Epoch 7/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 860.2978 - mae: 15.2177 - smape: 80.5086 - val_loss: 1512.6333 - val_mae: 17.2793 - val_smape: 81.4114
Epoch 8/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 728.5285 - mae: 15.1708 - smape: 80.2971 - val_loss: 5747.3486 - val_mae: 19.3280 - val_smape: 80.7531
Epoch 9/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 739.0701 - mae: 15.2110 - smape: 80.6577 - val_loss: 10358.2246 - val_mae: 20.5223 - val_smape: 80.5592
Epoch 10/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 819.2250 - mae: 15.0143 - smape: 80.2859 - val_loss: 28953.7930 - val_mae: 23.6672 - val_smape: 80.4161
Epoch 11/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 736.4528 - mae: 15.0892 - smape: 80.2653 - val_loss: 21074.6484 - val_mae: 23.7649 - val_smape: 80.4863
Epoch 12/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - loss: 754.3285 - mae: 15.0136 - smape: 80.1558 - val_loss: 40919.1367 - val_mae: 25.2797 - val_smape: 80.0925
Epoch 13/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 726.9294 - mae: 14.8952 - smape: 80.2648 - val_loss: 41579.2031 - val_mae: 23.9318 - val_smape: 80.9456
Epoch 14/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 896.6401 - mae: 15.0266 - smape: 80.4948 - val_loss: 24813.4512 - val_mae: 23.3371 - val_smape: 80.9863
Epoch 15/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 686.2001 - mae: 14.7350 - smape: 80.3623 - val_loss: 13222.1133 - val_mae: 19.9723 - val_smape: 79.7623
Epoch 16/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 945.4051 - mae: 15.0994 - smape: 80.8840 - val_loss: 39005.9102 - val_mae: 21.6669 - val_smape: 80.3430
Epoch 17/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 706.0534 - mae: 14.7161 - smape: 80.5293 - val_loss: 344777.6875 - val_mae: 37.5513 - val_smape: 80.6354
Epoch 18/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 741.3683 - mae: 14.8707 - smape: 79.9667 - val_loss: 26601.3555 - val_mae: 21.6902 - val_smape: 80.0800
Epoch 19/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 846.7723 - mae: 15.0140 - smape: 80.4587 - val_loss: 903958.1875 - val_mae: 54.1768 - val_smape: 80.8034
Epoch 20/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 1086.8622 - mae: 15.1452 - smape: 80.4471 - val_loss: 309497.3438 - val_mae: 35.9986 - val_smape: 80.4006
Epoch 21/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 641.0266 - mae: 14.7895 - smape: 79.9975 - val_loss: 88529.6016 - val_mae: 29.5481 - val_smape: 80.0277
Epoch 22/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - loss: 647.5885 - mae: 14.7729 - smape: 80.1008 - val_loss: 264347.9375 - val_mae: 34.2488 - val_smape: 80.9286
Epoch 23/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 798.1692 - mae: 14.8303 - smape: 80.0990 - val_loss: 181922.9219 - val_mae: 34.1347 - val_smape: 80.6251
Epoch 24/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 793.1095 - mae: 14.9679 - smape: 80.1294 - val_loss: 112994.1016 - val_mae: 28.2097 - val_smape: 81.4537
Epoch 25/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 714.7493 - mae: 14.7485 - smape: 80.1107 - val_loss: 173530.2344 - val_mae: 28.9960 - val_smape: 80.7825
Epoch 26/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 676.0988 - mae: 14.7486 - smape: 80.3965 - val_loss: 371441.5000 - val_mae: 40.8415 - val_smape: 80.8687
Epoch 27/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 687.2217 - mae: 14.7384 - smape: 80.1168 - val_loss: 820863.5625 - val_mae: 51.5747 - val_smape: 80.1664
Epoch 28/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - loss: 626.2453 - mae: 14.5830 - smape: 80.0349 - val_loss: 208663.9062 - val_mae: 28.9277 - val_smape: 79.8686
Epoch 29/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 730.4490 - mae: 14.8034 - smape: 80.1631 - val_loss: 361915.4062 - val_mae: 36.8848 - val_smape: 80.6898
Epoch 30/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 755.8210 - mae: 14.8325 - smape: 80.4444 - val_loss: 766788.5000 - val_mae: 52.0376 - val_smape: 79.6291
Epoch 31/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 753.0393 - mae: 14.5829 - smape: 79.7582 - val_loss: 1656058.5000 - val_mae: 67.0778 - val_smape: 80.7357
Epoch 32/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 671.7532 - mae: 14.4531 - smape: 80.0351 - val_loss: 718676.8125 - val_mae: 45.6927 - val_smape: 81.5071
Epoch 33/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 656.3448 - mae: 14.7869 - smape: 80.3525 - val_loss: 429942.9062 - val_mae: 37.8751 - val_smape: 79.3820
Epoch 34/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 876.0671 - mae: 14.6500 - smape: 80.1776 - val_loss: 1810106.8750 - val_mae: 71.7743 - val_smape: 80.3951
Epoch 35/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 654.9303 - mae: 14.7081 - smape: 80.3560 - val_loss: 9638115.0000 - val_mae: 127.5525 - val_smape: 80.5144
Epoch 36/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 821.1486 - mae: 14.8728 - smape: 80.1887 - val_loss: 2406899.0000 - val_mae: 73.6987 - val_smape: 80.5004
Epoch 37/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 737.9578 - mae: 14.6394 - smape: 79.6743 - val_loss: 16658353.0000 - val_mae: 171.7998 - val_smape: 79.9782
Epoch 38/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 715.2821 - mae: 14.5088 - smape: 79.6201 - val_loss: 13330658.0000 - val_mae: 167.0520 - val_smape: 81.8509
Epoch 39/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 633.6975 - mae: 14.4459 - smape: 80.0764 - val_loss: 1583286.3750 - val_mae: 63.9895 - val_smape: 79.8535
Epoch 40/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 775.4330 - mae: 14.6453 - smape: 80.1827 - val_loss: 6273538.0000 - val_mae: 111.4397 - val_smape: 80.7680
Epoch 41/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 630.4848 - mae: 14.5513 - smape: 80.2162 - val_loss: 8313952.5000 - val_mae: 124.3012 - val_smape: 80.9234
Epoch 42/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 584.7808 - mae: 14.2990 - smape: 79.8505 - val_loss: 3991196.2500 - val_mae: 100.0935 - val_smape: 81.7016
Epoch 43/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 613.3320 - mae: 14.5812 - smape: 80.0611 - val_loss: 4786619.5000 - val_mae: 110.0714 - val_smape: 81.1093
Epoch 44/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 693.0115 - mae: 14.5145 - smape: 79.8869 - val_loss: 34109004.0000 - val_mae: 219.7232 - val_smape: 80.4235
Epoch 45/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 675.3594 - mae: 14.5976 - smape: 80.1583 - val_loss: 48074320.0000 - val_mae: 304.4397 - val_smape: 81.5505
Epoch 46/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 614.4116 - mae: 14.6289 - smape: 80.1965 - val_loss: 17129660.0000 - val_mae: 197.9090 - val_smape: 80.3114
Epoch 47/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 651.6287 - mae: 14.6733 - smape: 79.8265 - val_loss: 3692632.7500 - val_mae: 137.9891 - val_smape: 81.8588
Epoch 48/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 643.4952 - mae: 14.4778 - smape: 80.0265 - val_loss: 51446132.0000 - val_mae: 320.0867 - val_smape: 82.1236
Epoch 49/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 620.2662 - mae: 14.3435 - smape: 79.9626 - val_loss: 18779776.0000 - val_mae: 208.8691 - val_smape: 81.8063
Epoch 50/50
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 708.9126 - mae: 14.6664 - smape: 80.1532 - val_loss: 8206181.5000 - val_mae: 155.8576 - val_smape: 81.0131

In [ ]:
df_test_X=pd.df_train=pd.read_csv(url,nrows=20000)

In [ ]:
text_x=df_test_X.loc[10000:11000,:]

In [ ]:
text_x

,sample_id,catalog_content,image_link,price
10000,144360,Item Name: Oak Smoke Decaf Black Tea (Loose) (...,https://m.media-amazon.com/images/I/81GdsREBZw...,27.40
10001,31120,Item Name: International Collection Virgin Fla...,https://m.media-amazon.com/images/I/813xJZ-8Z5...,12.49
10002,239791,Item Name: Warheads Limited Edition Halloween ...,https://m.media-amazon.com/images/I/81zerWnK-A...,12.99
10003,90802,"Item Name: Swad Cardamom Seed, 14 Ounce\nBulle...",https://m.media-amazon.com/images/I/91UA80t+nK...,25.99
10004,114112,"Item Name: Ruffles Potato Chips, Lime & Jalape...",https://m.media-amazon.com/images/I/71l0W92MCB...,4.79
...,...,...,...,...
10996,17609,Item Name: Eight O'Clock Coffee Donut Shop Gro...,https://m.media-amazon.com/images/I/81ThYL4cvG...,14.32
10997,144717,"Item Name: La Croix Sparkling Water, Passion F...",https://m.media-amazon.com/images/I/81jzN2pYxz...,4.19
10998,37050,Item Name: Progresso Garden Vegetable Classics...,https://m.media-amazon.com/images/I/917-Tz1ROZ...,2.38
10999,115527,Item Name: San Antonio Dulce de Leche Classic ...,https://m.media-amazon.com/images/I/71U0zbHKUv...,15.99
11000,247846,"Item Name: Alani Nu TROPSICLE Sugar Free, Low ...",https://m.media-amazon.com/images/I/71ENCmXeUI...,2.48

In [ ]:
textinp=get_text_embeddings_mpnet(text_x['catalog_content'].tolist())

100%|██████████| 1001/1001 [00:22<00:00, 44.81it/s]

In [ ]:
testimage = [get_image_embedding_effnet_imageLink(url) for url in tqdm(text_x['image_link'])]
testimage= np.array(testimage)

100%|██████████| 1001/1001 [03:01<00:00,  5.50it/s]

In [ ]:
def smape(y_true, y_pred):
    return 100 * np.mean(np.abs(y_true - y_pred) / ((np.abs(y_true) + np.abs(y_pred)) / 2))

In [ ]:
ytext1=text_x['price']

In [ ]:
preds_df = pd.DataFrame(preds, columns=['pred'])

# Concatenate along columns
mdfnew = pd.concat([preds_df, ytext1.reset_index(drop=True)], axis=1)

In [ ]:
mdfnew

          pred   price
0     2.991906   3.920
1     4.596334  10.465
2     2.725857   3.420
3    29.862772  39.990
4    39.728313  85.420
..         ...     ...
995  28.752169  22.990
996  20.369280   4.290
997   8.005280   9.900
998  23.428749   4.960
999  16.415594  12.990

[1000 rows x 2 columns]

In [ ]:
dfnew

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,2.991906,4.596334,2.725857,29.862772,39.728313,23.990362,20.690731,29.795309,23.858717,10.128128,...,22.460979,44.091972,18.11034,7.570084,23.075397,28.752169,20.36928,8.00528,23.428749,16.415594
1,3.920000,10.465000,3.420000,39.990000,85.420000,7.710000,1.480000,19.980000,35.990000,33.300000,...,8.745000,46.890000,5.49000,5.870000,23.500000,22.990000,4.29000,9.90000,4.960000,12.990000

In [ ]:
print("Valid", smape(y, ytext1))

Validation SMAPE: 94.53380319391648

IF Want to train with eff net bhi train ho toh ye

Ahh ab samajh gaya Keshav 😎 — tu basically **multi-modal regression** karna chahta hai:

* Input 1 → **Image** (EfficientNet fine-tune ho raha ho)
* Input 2 → **Text embeddings** (precomputed, e.g., MPNet 768-dim)
* Output → **Price prediction**

Yes, ye bilkul **possible hai**. Bas hume **Keras Functional API** ka use karna padega, kyunki Sequential API me multiple inputs directly handle nahi hote.

Main tujhe **step-by-step structure** bata deta hoon:

---

## 1️⃣ Image Input → EfficientNet

```python
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, GlobalAveragePooling2D, Input, Concatenate
from tensorflow.keras.models import Model
import tensorflow as tf

# Image input
img_input = Input(shape=(224,224,3))

base_model = EfficientNetB0(weights='imagenet', include_top=False, input_tensor=img_input)

# Freeze all layers first
for layer in base_model.layers:
    layer.trainable = False

# Fine-tune last 4 layers
for layer in base_model.layers[-4:]:
    layer.trainable = True

x_img = base_model.output
x_img = GlobalAveragePooling2D()(x_img)  # image embedding vector
x_img = Dense(512, activation='relu')(x_img)
x_img = BatchNormalization()(x_img)
x_img = Dropout(0.5)(x_img)
```

---

## 2️⃣ Text Input → Precomputed embeddings

```python
# Suppose text embeddings = 768-dim
text_input = Input(shape=(768,))
x_text = Dense(512, activation='relu')(text_input)
x_text = BatchNormalization()(x_text)
x_text = Dropout(0.5)(x_text)
```

---

## 3️⃣ Combine Image + Text

```python
combined = Concatenate()([x_img, x_text])
x = Dense(512, activation='relu')(combined)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)
x = Dense(256, activation='relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)
output = Dense(1, activation='linear')(x)
```

---

## 4️⃣ Create Model & Compile

```python
model = Model(inputs=[img_input, text_input], outputs=output)

def smape(y_true, y_pred):
    epsilon = 1e-6
    numerator = tf.abs(y_true - y_pred)
    denominator = (tf.abs(y_true) + tf.abs(y_pred) + epsilon) / 2.0
    return 100 * tf.reduce_mean(numerator / denominator)

model.compile(optimizer='adam', loss=smape, metrics=['mae','mse'])
model.summary()
```

---

## 5️⃣ Training

```python
# Suppose X_img = images as numpy array (224,224,3)
# X_text = precomputed embeddings (768-dim)
# y = price

model.fit([X_img, X_text], y, batch_size=32, epochs=10)
```

---

### 🔹 Notes:

1. EfficientNet **last 4 layers trainable** → model images ke features update karega
2. Text embeddings **freeze** → fast aur memory efficient, agar chahe to text branch bhi trainable kar sakta hai
3. Concatenate → dono modalities ke features ek saath regression head me jaate hain
4. Agar GPU memory kam ho → fine-tune **last 2 layers** instead of 4

---

Agar tu chaahe to mai **tere existing image folder + text embeddings se full working multi-modal model ka ready-to-run code** bana du jisme EfficientNet fine-tune + text embeddings input ho, aur tu seedha train kar sake.

Chaahe mai wo bana du?

In [ ]:
n